# Generated by Django 5.2.5 on 2025-08-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_slug",
            field=models.SlugField(default=262626262, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="department_slug",
            field=models.SlugField(default=262626226, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_slug",
            field=models.SlugField(default=161616161, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_slug",
            field=models.SlugField(default=161616161, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
